[theme]
base = "light"
primaryColor = "#91181B"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F7EFEC"
textColor = "#2B2B2B"
font = "sans serif"

[server]
maxUploadSize = 200
headless = true

[browser]
gatherUsageStats = false

[client]
toolbarMode = "minimal"
